/* Uso Inmueble */
INSERT INTO sistema_gestor_asociados_usoinmueble (id, nombre) VALUES (1, 'Rentado'), (2, 'Propietario'), (3, 'Otro');
/* Generos */
INSERT INTO sistema_gestor_asociados_genero (id, nombre) VALUES (1, 'Femenino'), (2, 'Masculino'), (3, 'Otro');
/* Parentescos */
INSERT INTO sistema_gestor_asociados_parentesco (id, nombre) VALUES (1, 'Madre'), (2, 'Padre'), (3, 'Hermano/a'), (4, 'Hijo/a'), (5, 'Esposo/a');
/* Tipo Documento */
INSERT INTO sistema_gestor_asociados_tipodocumento (id, nombre) VALUES (1,'DUI'), (2,'Pasaporte');
/* Estado Civil */
INSERT INTO sistema_gestor_asociados_estadofamiliar (id, nombre) VALUES (1,'Soltero/a'), (2,'Casado/a'), (3,'Viudo/a'), (4,'Divorciado/a');
/* Tipo Trabajador */
INSERT INTO sistema_gestor_asociados_tipotrabajador (id, nombre) VALUES (1,'Empleado'), (2, 'Empresario'), (3, 'Empleado y Empresario');
/* Rubros */
INSERT INTO sistema_gestor_asociados_rubro(Id,nombre) VALUES (1,'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA');
INSERT INTO sistema_gestor_asociados_rubro(Id,nombre) VALUES (2,'EXPLOTACIÓN DE MINAS Y CANTERAS');
INSERT INTO sistema_gestor_asociados_rubro(Id,nombre) VALUES (3,'INDUSTRIAS MANUFACTURERAS');
INSERT INTO sistema_gestor_asociados_rubro(Id,nombre) VALUES (4,'SUMINISTROS DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO');

/* Asociados */
INSERT INTO sistema_gestor_asociados_asociado (id, nacionalidad_id, pais_nacimiento_id, tipo_documento_id, numero_identidad, fecha_nacimiento,
genero_id, nombres, estado_familiar_id, primer_apellido, segundo_apellido, salario, tipo_trabajador_id, estado_aprobado, estado_pagado) VALUES 
(1, 59, 59, 1, '034258210','2003-07-23',1,'Isabella Irene',1,'Martinez','Corranza',1000, 1,FALSE ,FALSE),
(2, 59, 59, 1, '035612320','2004-07-23',1,'Emma Adelaide',1,'Acatio','Segovia',1000, 1,FALSE ,FALSE),
(3, 59, 59, 1, '162338210','2005-07-23',1,'Laura Gianna',1,'Contanza','Estrada',1000, 1,TRUE ,TRUE),
(4, 59, 23, 1, '045666210','2000-07-23',2,'Carlos Mauricio',1,'Menendez','Rada',1000, 1,TRUE ,TRUE);


/*
CREATE TABLE sistema_gestor_asociados_paises(
   id             INTEGER  NOT NULL PRIMARY KEY 
  ,nombre         VARCHAR(54) NOT NULL
  ,alfa_2         VARCHAR(2) NOT NULL
  ,alfa_3         VARCHAR(3) NOT NULL
  ,alpha_numerico INTEGER  NOT NULL
);
*/
/* Paises */
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (1,'Afganistán','AF','AFG',4);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (2,'Åland, Islas','AX','ALA',248);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (3,'Albania','AL','ALB',8);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (4,'Alemania','DE','DEU',276);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (5,'Andorra','AD','AND',20);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (6,'Angola','AO','AGO',24);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (7,'Anguila','AI','AIA',660);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (8,'Antártida','AQ','ATA',10);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (9,'Antigua y Barbuda','AG','ATG',28);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (10,'Arabia Saudita','SA','SAU',682);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (11,'Argelia','DZ','DZA',12);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (12,'Argentina','AR','ARG',32);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (13,'Armenia','AM','ARM',51);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (14,'Aruba','AW','ABW',533);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (15,'Australia','AU','AUS',36);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (16,'Austria','AT','AUT',40);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (17,'Azerbaiyán','AZ','AZE',31);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (18,'Bahamas (las)','BS','BHS',44);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (19,'Bangladés','BD','BGD',50);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (20,'Barbados','BB','BRB',52);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (21,'Baréin','BH','BHR',48);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (22,'Bélgica','BE','BEL',56);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (23,'Belice','BZ','BLZ',84);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (24,'Benín','BJ','BEN',204);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (25,'Bermudas','BM','BMU',60);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (26,'Belarús','BY','BLR',112);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (27,'Bolivia (Estado Plurinacional de)','BO','BOL',68);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (28,'Bonaire, San Eustaquio y Saba','BQ','BES',535);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (29,'Bosnia y Herzegovina','BA','BIH',70);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (30,'Botsuana','BW','BWA',72);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (31,'Brasil','BR','BRA',76);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (32,'Brunéi Darussalam','BN','BRN',96);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (33,'Bulgaria','BG','BGR',100);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (34,'Burkina Faso','BF','BFA',854);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (35,'Burundi','BI','BDI',108);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (36,'Bhután','BT','BTN',64);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (37,'Cabo Verde','CV','CPV',132);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (38,'Camboya','KH','KHM',116);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (39,'Camerún','CM','CMR',120);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (40,'Canadá','CA','CAN',124);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (41,'Catar','QA','QAT',634);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (42,'Chad','TD','TCD',148);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (43,'Chile','CL','CHL',152);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (44,'China','CN','CHN',156);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (45,'Chipre','CY','CYP',196);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (46,'Colombia','CO','COL',170);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (47,'Comoras (las)','KM','COM',174);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (48,'Corea (la República Popular Democrática de)','KP','PRK',408);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (49,'Corea (la República de)','KR','KOR',410);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (50,'Côte d''Ivoire','CI','CIV',384);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (51,'Costa Rica','CR','CRI',188);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (52,'Croacia','HR','HRV',191);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (53,'Cuba','CU','CUB',192);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (54,'Curaçao','CW','CUW',531);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (55,'Dinamarca','DK','DNK',208);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (56,'Dominica','DM','DMA',212);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (57,'Ecuador','EC','ECU',218);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (58,'Egipto','EG','EGY',818);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (59,'El Salvador','SV','SLV',222);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (60,'Emiratos Árabes Unidos (los)','AE','ARE',784);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (61,'Eritrea','ER','ERI',232);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (62,'Eslovaquia','SK','SVK',703);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (63,'Eslovenia','SI','SVN',705);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (64,'España','ES','ESP',724);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (65,'Estados Unidos de América (los)','US','USA',840);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (66,'Estonia','EE','EST',233);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (67,'Etiopía','ET','ETH',231);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (68,'Filipinas (las)','PH','PHL',608);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (69,'Finlandia','FI','FIN',246);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (70,'Fiyi','FJ','FJI',242);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (71,'Francia','FR','FRA',250);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (72,'Gabón','GA','GAB',266);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (73,'Gambia (la)','GM','GMB',270);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (74,'Georgia','GE','GEO',268);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (75,'Ghana','GH','GHA',288);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (76,'Gibraltar','GI','GIB',292);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (77,'Granada','GD','GRD',308);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (78,'Grecia','GR','GRC',300);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (79,'Groenlandia','GL','GRL',304);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (80,'Guadeloupe','GP','GLP',312);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (81,'Guam','GU','GUM',316);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (82,'Guatemala','GT','GTM',320);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (83,'Guayana Francesa','GF','GUF',254);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (84,'Guernsey','GG','GGY',831);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (85,'Guinea','GN','GIN',324);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (86,'Guinea Bissau','GW','GNB',624);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (87,'Guinea Ecuatorial','GQ','GNQ',226);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (88,'Guyana','GY','GUY',328);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (89,'Haití','HT','HTI',332);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (90,'Honduras','HN','HND',340);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (91,'Hong Kong','HK','HKG',344);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (92,'Hungría','HU','HUN',348);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (93,'India','IN','IND',356);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (94,'Indonesia','ID','IDN',360);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (95,'Irak','IQ','IRQ',368);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (96,'Irán (República Islámica de)','IR','IRN',364);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (97,'Irlanda','IE','IRL',372);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (98,'Bouvet, Isla','BV','BVT',74);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (99,'Isla de Man','IM','IMN',833);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (100,'Navidad, Isla de','CX','CXR',162);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (101,'Islandia','IS','ISL',352);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (102,'Caimán, (las) Islas','KY','CYM',136);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (103,'Cocos / Keeling, (las) Islas','CC','CCK',166);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (104,'Cook, (las) Islas','CK','COK',184);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (105,'Feroe, (las) Islas','FO','FRO',234);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (106,'Georgia del Sur (la) y las Islas Sandwich del Sur','GS','SGS',239);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (107,'Heard (Isla) e Islas McDonald','HM','HMD',334);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (108,'Malvinas [Falkland], (las) Islas','FK','FLK',238);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (109,'Marianas del Norte, (las) Islas','MP','MNP',580);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (110,'Marshall, (las) Islas','MH','MHL',584);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (111,'Pitcairn','PN','PCN',612);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (112,'Salomón, Islas','SB','SLB',90);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (113,'Turcas y Caicos, (las) Islas','TC','TCA',796);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (114,'Islas Ultramarinas Menores de los Estados Unidos (las)','UM','UMI',581);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (115,'Vírgenes británicas, Islas','VG','VGB',92);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (116,'Vírgenes de los Estados Unidos, Islas','VI','VIR',850);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (117,'Israel','IL','ISR',376);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (118,'Italia','IT','ITA',380);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (119,'Jamaica','JM','JAM',388);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (120,'Japón','JP','JPN',392);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (121,'Jersey','JE','JEY',832);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (122,'Jordania','JO','JOR',400);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (123,'Kazajistán','KZ','KAZ',398);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (124,'Kenia','KE','KEN',404);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (125,'Kirguistán','KG','KGZ',417);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (126,'Kiribati','KI','KIR',296);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (127,'Kuwait','KW','KWT',414);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (128,'Lao, (la) República Democrática Popular','LA','LAO',418);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (129,'Lesoto','LS','LSO',426);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (130,'Letonia','LV','LVA',428);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (131,'Líbano','LB','LBN',422);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (132,'Liberia','LR','LBR',430);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (133,'Libia','LY','LBY',434);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (134,'Liechtenstein','LI','LIE',438);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (135,'Lituania','LT','LTU',440);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (136,'Luxemburgo','LU','LUX',442);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (137,'Macao','MO','MAC',446);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (138,'Macedonia del Norte','MK','MKD',807);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (139,'Madagascar','MG','MDG',450);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (140,'Malasia','MY','MYS',458);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (141,'Malawi','MW','MWI',454);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (142,'Maldivas','MV','MDV',462);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (143,'Malí','ML','MLI',466);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (144,'Malta','MT','MLT',470);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (145,'Marruecos','MA','MAR',504);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (146,'Martinique','MQ','MTQ',474);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (147,'Mauricio','MU','MUS',480);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (148,'Mauritania','MR','MRT',478);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (149,'Mayotte','YT','MYT',175);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (150,'México','MX','MEX',484);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (151,'Micronesia (Estados Federados de)','FM','FSM',583);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (152,'Moldavia (la República de)','MD','MDA',498);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (153,'Mónaco','MC','MCO',492);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (154,'Mongolia','MN','MNG',496);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (155,'Montenegro','ME','MNE',499);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (156,'Montserrat','MS','MSR',500);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (157,'Mozambique','MZ','MOZ',508);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (158,'Myanmar','MM','MMR',104);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (159,'Namibia','NA','NAM',516);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (160,'Nauru','NR','NRU',520);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (161,'Nepal','NP','NPL',524);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (162,'Nicaragua','NI','NIC',558);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (163,'Níger (el)','NE','NER',562);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (164,'Nigeria','NG','NGA',566);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (165,'Niue','NU','NIU',570);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (166,'Norfolk, Isla','NF','NFK',574);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (167,'Noruega','NO','NOR',578);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (168,'Nueva Caledonia','NC','NCL',540);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (169,'Nueva Zelandia','NZ','NZL',554);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (170,'Omán','OM','OMN',512);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (171,'Países Bajos (los)','NL','NLD',528);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (172,'Pakistán','PK','PAK',586);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (173,'Palaos','PW','PLW',585);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (174,'Palestina, Estado de','PS','PSE',275);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (175,'Panamá','PA','PAN',591);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (176,'Papúa Nueva Guinea','PG','PNG',598);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (177,'Paraguay','PY','PRY',600);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (178,'Perú','PE','PER',604);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (179,'Polinesia Francesa','PF','PYF',258);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (180,'Polonia','PL','POL',616);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (181,'Portugal','PT','PRT',620);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (182,'Puerto Rico','PR','PRI',630);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (183,'Reino Unido de Gran Bretaña e Irlanda del Norte (el)','GB','GBR',826);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (184,'Sahara Occidental','EH','ESH',732);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (185,'República Centroafricana (la)','CF','CAF',140);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (186,'Chequia','CZ','CZE',203);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (187,'Congo (el)','CG','COG',178);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (188,'Congo (la República Democrática del)','CD','COD',180);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (189,'Dominicana, (la) República','DO','DOM',214);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (190,'Reunión','RE','REU',638);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (191,'Ruanda','RW','RWA',646);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (192,'Rumania','RO','ROU',642);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (193,'Rusia, (la) Federación de','RU','RUS',643);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (194,'Samoa','WS','WSM',882);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (195,'Samoa Americana','AS','ASM',16);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (196,'Saint Barthélemy','BL','BLM',652);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (197,'San Cristóbal y Nieves','KN','KNA',659);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (198,'San Marino','SM','SMR',674);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (199,'Saint Martin (parte francesa)','MF','MAF',663);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (200,'San Pedro y Miquelón','PM','SPM',666);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (201,'San Vicente y las Granadinas','VC','VCT',670);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (202,'Santa Helena, Ascensión y Tristán de Acuña','SH','SHN',654);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (203,'Santa Lucía','LC','LCA',662);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (204,'Santo Tomé y Príncipe','ST','STP',678);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (205,'Senegal','SN','SEN',686);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (206,'Serbia','RS','SRB',688);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (207,'Seychelles','SC','SYC',690);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (208,'Sierra leona','SL','SLE',694);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (209,'Singapur','SG','SGP',702);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (210,'Sint Maarten (parte neerlandesa)','SX','SXM',534);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (211,'República Árabe Siria','SY','SYR',760);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (212,'Somalia','SO','SOM',706);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (213,'Sri Lanka','LK','LKA',144);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (214,'Suazilandia','SZ','SWZ',748);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (215,'Sudáfrica','ZA','ZAF',710);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (216,'Sudán (el)','SD','SDN',729);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (217,'Sudán del Sur','SS','SSD',728);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (218,'Suecia','SE','SWE',752);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (219,'Suiza','CH','CHE',756);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (220,'Suriname','SR','SUR',740);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (221,'Svalbard y Jan Mayen','SJ','SJM',744);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (222,'Tailandia','TH','THA',764);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (223,'Taiwán (Provincia de China)','TW','TWN',158);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (224,'Tanzania, República Unida de','TZ','TZA',834);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (225,'Tayikistán','TJ','TJK',762);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (226,'Territorio Británico del Océano Índico (el)','IO','IOT',86);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (227,'Tierras Australes Francesas (las)','TF','ATF',260);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (228,'Timor-Leste','TL','TLS',626);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (229,'Togo','TG','TGO',768);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (230,'Tokelau','TK','TKL',772);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (231,'Tonga','TO','TON',776);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (232,'Trinidad y Tobago','TT','TTO',780);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (233,'Túnez','TN','TUN',788);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (234,'Turkmenistán','TM','TKM',795);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (235,'Turquía','TR','TUR',792);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (236,'Tuvalu','TV','TUV',798);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (237,'Ucrania','UA','UKR',804);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (238,'Uganda','UG','UGA',800);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (239,'Uruguay','UY','URY',858);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (240,'Uzbekistán','UZ','UZB',860);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (241,'Vanuatu','VU','VUT',548);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (242,'Santa Sede (la)','VA','VAT',336);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (243,'Venezuela (República Bolivariana de)','VE','VEN',862);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (244,'Viet Nam','VN','VNM',704);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (245,'Wallis y Futuna','WF','WLF',876);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (246,'Yemen','YE','YEM',887);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (247,'Yibuti','DJ','DJI',262);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (248,'Zambia','ZM','ZMB',894);
INSERT INTO sistema_gestor_asociados_pais(id,nombre,alfa_2,alfa_3,alfa_numerico) VALUES (249,'Zimbabue','ZW','ZWE',716);
